server:
  port: 8082
spring:
  datasource:
    platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
    hikari:
      connectionTimeout: 300000
      maximumPoolSize: 60
  jpa:
    database: H2
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true